# Usage

In [2]:
import os
from dotenv import load_dotenv
from openbb import obb

if 'info' in obb.reference:
    obj = obb.reference["info"]["extensions"]["openbb_provider_extension"]
    print([item for item in obj if "akshare" in item])
    print([item for item in obj if "tushare" in item])

symbols = "601919,600519,000001,00300"
symbols_a = "601919,600519,000001,600325,600028,600036,430047"
symbol_a = "600325"
symbol_hk = "01658"
provider = "akshare"

os.environ["AKSHARE_API_KEY"] = obb.user.credentials.akshare_api_key.get_secret_value()
os.environ["TUSHARE_API_KEY"] = obb.user.credentials.tushare_api_key.get_secret_value()

#load_dotenv() 
akshare_api_key = os.environ.get("AKSHARE_API_KEY")
if akshare_api_key is None:
    raise ValueError("AKSHARE_API_KEY environment variable not set.")

tushare_api_key = os.environ.get("TUSHARE_API_KEY")
if tushare_api_key is None:
    raise ValueError("TUSHARE_API_KEY environment variable not set.")

['akshare@1.1.2']
['tushare@1.0.0']

In [ ]:
from openbb_core.app.service.user_service import UserService
from pathlib import Path
 
# 读取用户设置
settings = UserService.read_from_file()
cache_dir = Path(settings.preferences.cache_directory)
 
# 在数据目录下创建SQLite数据库
db_path = cache_dir / "appdata/equity.db"
#conn = sqlite3.connect(db_path)

In [2]:
from openbb_app import project_name
print(project_name)

openbb_app

## Equity histrical price

In [16]:
obb.equity.price.historical(symbol="600325", provider='akshare', use_cache=True, start_date="2026-01-01",end_date="2026-03-08").to_dataframe().tail()

2026-03-10 10:15:54,640 - openbb_akshare.utils.helpers - WARNING - Cache for 600325 is not up-to-date. Last date in cache: 2025-10-24, expected: 2026-03-09.
2026-03-10 10:15:55,181 - openbb_akshare.utils.helpers - INFO - Getting equity 600325 historical data from cache...

,open,high,low,close,volume,amount,change,change_percent
date,,,,,,,,
2026-03-02,4.27,4.35,4.21,4.29,688264,294697835.0,-0.02,-0.46
2026-03-03,4.30,4.32,4.11,4.14,792489,331898098.0,-0.15,-3.50
2026-03-04,4.10,4.17,4.05,4.09,446751,183444974.0,-0.05,-1.21
2026-03-05,4.13,4.16,4.07,4.10,418249,171218794.0,0.01,0.24
2026-03-06,4.08,4.14,4.07,4.13,398240,163408108.0,0.03,0.73

In [14]:
obb.equity.price.historical(symbol="600325.SH", provider='tushare', use_cache=True, start_date="2026-01-01",end_date="2026-03-08").to_dataframe().tail()

2026-03-10 10:13:07,074 - openbb_tushare.utils.ts_equity_historical - WARNING - Cache for 600325.SH is not up-to-date. Last date in cache: NaT, expected: 2026-03-09.
2026-03-10 10:13:07,930 - openbb_tushare.utils.ts_equity_historical - INFO - Downloaed historical data 600325.SH: 5264.
2026-03-10 10:13:07,969 - openbb_tushare.utils.ts_equity_historical - INFO - Getting equity 600325.SH historical data from cache...

,open,high,low,close,volume,amount,change,change_percent,pre_close
date,,,,,,,,,
2026-03-02,4.27,4.35,4.21,4.29,688263.70,294697.835,-0.02,-0.4640,4.31
2026-03-03,4.30,4.32,4.11,4.14,792488.62,331898.098,-0.15,-3.4965,4.29
2026-03-04,4.10,4.17,4.05,4.09,446751.02,183444.974,-0.05,-1.2077,4.14
2026-03-05,4.13,4.16,4.07,4.10,418248.80,171218.794,0.01,0.2445,4.09
2026-03-06,4.08,4.14,4.07,4.13,398240.00,163408.108,0.03,0.7317,4.10

In [15]:
obb.equity.price.historical(symbol="600325.SS", provider='yfinance', use_cache=True, start_date="2026-01-01",end_date="2026-03-08").to_dataframe().tail()

            open  high   low  close    volume
date
2026-03-02  4.27  4.35  4.21   4.29  68826370
2026-03-03  4.30  4.32  4.11   4.14  79248862
2026-03-04  4.10  4.17  4.05   4.09  44675102
2026-03-05  4.13  4.16  4.07   4.10  41824880
2026-03-06  4.08  4.14  4.07   4.13  39824000

## Equity profile

In [5]:
obb.equity.profile(symbol="00386", provider='akshare', use_cache=True).to_dataframe().tail()

Error fetching equity info for 00386: 'data'

OpenBBError:
[Error] -> Error getting data for 00386 -> IndexError: list index out of range