# Usage

In [1]:
import os
from dotenv import load_dotenv
from openbb import obb

if 'info' in obb.reference:
    obj = obb.reference["info"]["extensions"]["openbb_provider_extension"]
    print([item for item in obj if "akshare" in item])
    print([item for item in obj if "tushare" in item])

symbols = "601919,600519,000001,00300"
symbols_a = "601919,600519,000001,600325,600028,600036,430047"
symbol_a = "600325"
symbol_hk = "01658"
provider = "akshare"

os.environ["AKSHARE_API_KEY"] = obb.user.credentials.akshare_api_key.get_secret_value()
os.environ["TUSHARE_API_KEY"] = obb.user.credentials.tushare_api_key.get_secret_value()

#load_dotenv() 
akshare_api_key = os.environ.get("AKSHARE_API_KEY")
if akshare_api_key is None or akshare_api_key == "":
    raise ValueError("AKSHARE_API_KEY environment variable not set.")

tushare_api_key = os.environ.get("TUSHARE_API_KEY")
if tushare_api_key is None or tushare_api_key == "":
    raise ValueError("TUSHARE_API_KEY environment variable not set.")

['akshare@1.1.3']
['tushare@1.0.0']

In [ ]:
obb.user.credentials.tushare_api_key="dummy_key"
from openbb_core.app.service.user_service import UserService
u = UserService.read_from_file()
u.credentials.tushare_api_key="dummy_key"
UserService.write_to_file(u)

In [ ]:
from openbb_core.app.service.user_service import UserService
from pathlib import Path
 
# 读取用户设置
settings = UserService.read_from_file()
cache_dir = Path(settings.preferences.cache_directory)
 
# 在数据目录下创建SQLite数据库
db_path = cache_dir / "appdata/equity.db"
#conn = sqlite3.connect(db_path)

In [2]:
from openbb_app import project_name
print(project_name)

openbb_app

## Equity histrical price

In [16]:
obb.equity.price.historical(symbol="600325", provider='akshare', use_cache=True, start_date="2026-01-01",end_date="2026-03-08").to_dataframe().tail()

2026-03-10 10:15:54,640 - openbb_akshare.utils.helpers - WARNING - Cache for 600325 is not up-to-date. Last date in cache: 2025-10-24, expected: 2026-03-09.
2026-03-10 10:15:55,181 - openbb_akshare.utils.helpers - INFO - Getting equity 600325 historical data from cache...

,open,high,low,close,volume,amount,change,change_percent
date,,,,,,,,
2026-03-02,4.27,4.35,4.21,4.29,688264,294697835.0,-0.02,-0.46
2026-03-03,4.30,4.32,4.11,4.14,792489,331898098.0,-0.15,-3.50
2026-03-04,4.10,4.17,4.05,4.09,446751,183444974.0,-0.05,-1.21
2026-03-05,4.13,4.16,4.07,4.10,418249,171218794.0,0.01,0.24
2026-03-06,4.08,4.14,4.07,4.13,398240,163408108.0,0.03,0.73

In [14]:
obb.equity.price.historical(symbol="600325.SH", provider='tushare', use_cache=True, start_date="2026-01-01",end_date="2026-03-08").to_dataframe().tail()

2026-03-10 10:13:07,074 - openbb_tushare.utils.ts_equity_historical - WARNING - Cache for 600325.SH is not up-to-date. Last date in cache: NaT, expected: 2026-03-09.
2026-03-10 10:13:07,930 - openbb_tushare.utils.ts_equity_historical - INFO - Downloaed historical data 600325.SH: 5264.
2026-03-10 10:13:07,969 - openbb_tushare.utils.ts_equity_historical - INFO - Getting equity 600325.SH historical data from cache...

,open,high,low,close,volume,amount,change,change_percent,pre_close
date,,,,,,,,,
2026-03-02,4.27,4.35,4.21,4.29,688263.70,294697.835,-0.02,-0.4640,4.31
2026-03-03,4.30,4.32,4.11,4.14,792488.62,331898.098,-0.15,-3.4965,4.29
2026-03-04,4.10,4.17,4.05,4.09,446751.02,183444.974,-0.05,-1.2077,4.14
2026-03-05,4.13,4.16,4.07,4.10,418248.80,171218.794,0.01,0.2445,4.09
2026-03-06,4.08,4.14,4.07,4.13,398240.00,163408.108,0.03,0.7317,4.10

In [15]:
obb.equity.price.historical(symbol="600325.SS", provider='yfinance', use_cache=True, start_date="2026-01-01",end_date="2026-03-08").to_dataframe().tail()

            open  high   low  close    volume
date
2026-03-02  4.27  4.35  4.21   4.29  68826370
2026-03-03  4.30  4.32  4.11   4.14  79248862
2026-03-04  4.10  4.17  4.05   4.09  44675102
2026-03-05  4.13  4.16  4.07   4.10  41824880
2026-03-06  4.08  4.14  4.07   4.13  39824000

## Equity Search (股票搜索)

In [6]:
symbol_b="00144"
result = obb.equity.search(query=symbol_b, provider=provider).to_dataframe()
result[result['symbol'] == symbol_b]

2026-03-24 10:34:08,894 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...

2026-03-24 10:34:08,910 - openbb_akshare.models.equity_search - INFO - Searching for 00144 and found 2 results.

  symbol   name exchange
1  00144  招商局港口     HKEX

## Equity Key Metrics

In [9]:
symbol_f="00144.HK"
obb.equity.fundamental.metrics(symbol=symbol_f, provider=provider).to_dataframe().T

                           0
symbol                 00144
基本每股收益(元)          0.7788053
每股股息TTM(港元)            0.886
每股经营现金流(元)    0.768790849902
每股净资产(元)     23.384362765899
派息比率(%)                52.50
股息率TTM(%)               5.51
已发行股本(股)              41.98亿
总市值(港元)              661.61亿
已发行股本-H股(股)           41.98亿
港股市值(港元)             661.61亿

## Equity profile

In [2]:
obb.equity.profile(symbol="00386", provider='akshare', use_cache=True).to_dataframe().tail()

,symbol,name,ceo,company_url,business_address,mailing_address,business_phone_no,employees,industry_category,公司名称,公司简介,主要范围,上市日期,org_short_name_cn,org_short_name_en,org_id,actual_issue_vol,reg_asset,currency,成立日期
0,00386.HK,China Petroleum & Chemical Corporation,侯启军,http://www.sinopec.com,中国北京市朝阳区朝阳门北大街22号,香港湾仔港湾道1号会展广场办公大楼20楼,010-59960028,0,1.0,中国石油化工股份有限公司,中国石油化工股份有限公司(以下简称“中国石化”)是一家上中下游一体化、石油石化主业突...,本公司的主要业务包括:在中国勘探、开发及生产原油及天然气;管输原油、天然气;炼油;以...,2000-10-18,,,200001230.0,0,0.0,HKD,9.514080e+11

## Equity Quote (股票实时报价)

In [3]:
obb.equity.price.quote(symbols, provider=provider).to_dataframe().head()

2026-03-20 09:54:50,429 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH601919
2026-03-20 09:54:51,300 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600519
2026-03-20 09:54:52,133 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SZ000001
2026-03-20 09:54:52,952 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 00300

,symbol,name,exchange,open,high,low,volume,prev_close,change_percent,52_week_high,...,dividend_yield_ttm,currency,book_value_per_share,pe_ratio_static,turnover,pb_ratio,limit_up,pe_ratio_ttm,time,ps_ratio
0,SH601919,中远海控,SH,15.69,15.91,15.65,54536267,15.98,-0.75,16.9800,...,10.139,CNY,14.9946,7.8680,8.603788e+08,1.0580,17.58,7.868,2026-03-20 09:54:44,NaN
1,SH600519,贵州茅台,SH,1452.96,1462.50,1451.00,516130,1452.87,-0.13,1589.2626,...,3.559,CNY,205.2831,21.0730,7.514490e+08,7.0680,1598.16,20.183,2026-03-20 09:54:44,NaN
2,SZ000001,平安银行,SZ,10.87,10.94,10.85,19524512,10.88,0.37,13.0581,...,5.476,CNY,23.0800,4.7610,2.126249e+08,0.4730,11.97,4.915,2026-03-20 09:54:51,NaN
3,00300,美的集团,HK,84.90,84.90,83.75,238310,84.00,-0.30,95.0000,...,5.420,HKD,32.6044,15.5702,2.007152e+07,2.5931,NaN,13.554,2026-03-20 09:54:29,1.13

## Equity Data

In [1]:
from openbb_app.core.equity_data import EquityData
equity_data = EquityData()

In [2]:
from IPython.display import HTML, display
display(HTML(equity_data.get_screener(is_realized=True, market='HK')))

2026-03-27 11:51:34,851 - openbb_app.core.equity_data - INFO - Calling get_screener with is_realized=True, market=HK
2026-03-27 11:51:34,856 - openbb_app.core.equity_data - INFO - Fetching current prices from provider with is_realized=True: 00123,00144,00386,00728,00939,00998,01288,01339,01398,01658,01919,02800,02880,03988,06823
2026-03-27 11:51:34,858 - openbb_app.core.utils - INFO - Fetching quote data for 00123
2026-03-27 11:51:34,873 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 00123
2026-03-27 11:51:35,614 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00123
2026-03-27 11:51:35,616 - openbb_app.core.utils - INFO - Fetching quote data for 00144
2026-03-27 11:51:35,619 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 00144
2026-03-27 11:51:36,454 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00144
2026-03-27 11:51:36,455 - openbb_app.core.utils - INFO - Fetching quote data for 00386
2026-03-27 11:51:36,460 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 00386
2026-03-27 11:51:37,303 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00386
2026-03-27 11:51:37,304 - openbb_app.core.utils - INFO - Fetching quote data for 00728
2026-03-27 11:51:37,309 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 00728
2026-03-27 11:51:38,243 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00728
2026-03-27 11:51:38,243 - openbb_app.core.utils - INFO - Fetching quote data for 00939
2026-03-27 11:51:38,251 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 00939
2026-03-27 11:51:39,211 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00939
2026-03-27 11:51:39,213 - openbb_app.core.utils - INFO - Fetching quote data for 00998
2026-03-27 11:51:39,218 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 00998
2026-03-27 11:51:40,093 - openbb_app.core.utils - INFO - Successfully fetched quote data for 00998
2026-03-27 11:51:40,093 - openbb_app.core.utils - INFO - Fetching quote data for 01288
2026-03-27 11:51:40,098 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 01288
2026-03-27 11:51:40,896 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01288
2026-03-27 11:51:40,897 - openbb_app.core.utils - INFO - Fetching quote data for 01339
2026-03-27 11:51:40,901 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 01339
2026-03-27 11:51:41,810 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01339
2026-03-27 11:51:41,812 - openbb_app.core.utils - INFO - Fetching quote data for 01398
2026-03-27 11:51:41,817 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 01398
2026-03-27 11:51:42,655 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01398
2026-03-27 11:51:42,656 - openbb_app.core.utils - INFO - Fetching quote data for 01658
2026-03-27 11:51:42,661 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 01658
2026-03-27 11:51:43,459 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01658
2026-03-27 11:51:43,460 - openbb_app.core.utils - INFO - Fetching quote data for 01919
2026-03-27 11:51:43,466 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 01919
2026-03-27 11:51:44,353 - openbb_app.core.utils - INFO - Successfully fetched quote data for 01919
2026-03-27 11:51:44,354 - openbb_app.core.utils - INFO - Fetching quote data for 02800
2026-03-27 11:51:44,359 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 02800
2026-03-27 11:51:45,109 - openbb_app.core.utils - INFO - Successfully fetched quote data for 02800
2026-03-27 11:51:45,111 - openbb_app.core.utils - INFO - Fetching quote data for 02880
2026-03-27 11:51:45,116 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 02880
2026-03-27 11:51:45,992 - openbb_app.core.utils - INFO - Successfully fetched quote data for 02880
2026-03-27 11:51:45,993 - openbb_app.core.utils - INFO - Fetching quote data for 03988
2026-03-27 11:51:45,997 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 03988
2026-03-27 11:51:46,839 - openbb_app.core.utils - INFO - Successfully fetched quote data for 03988
2026-03-27 11:51:46,839 - openbb_app.core.utils - INFO - Fetching quote data for 06823
2026-03-27 11:51:46,844 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: 06823
2026-03-27 11:51:47,680 - openbb_app.core.utils - INFO - Successfully fetched quote data for 06823
2026-03-27 11:51:47,819 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 00123
2026-03-27 11:51:47,838 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:47,853 - openbb_akshare.models.equity_search - INFO - Searching for 00123 and found 9 results.
2026-03-27 11:51:47,856 - openbb_app.routes.portfolio - INFO - Found stock name for 00123: 越秀地产
2026-03-27 11:51:47,857 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 00144
2026-03-27 11:51:47,871 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:47,885 - openbb_akshare.models.equity_search - INFO - Searching for 00144 and found 2 results.
2026-03-27 11:51:47,890 - openbb_app.routes.portfolio - INFO - Found stock name for 00144: 招商局港口
2026-03-27 11:51:47,891 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 00386
2026-03-27 11:51:47,905 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:47,921 - openbb_akshare.models.equity_search - INFO - Searching for 00386 and found 3 results.
2026-03-27 11:51:47,924 - openbb_app.routes.portfolio - INFO - Found stock name for 00386: 中国石油化工股份
2026-03-27 11:51:47,925 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 00728
2026-03-27 11:51:47,939 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:47,953 - openbb_akshare.models.equity_search - INFO - Searching for 00728 and found 3 results.
2026-03-27 11:51:47,956 - openbb_app.routes.portfolio - INFO - Found stock name for 00728: 中国电信
2026-03-27 11:51:47,957 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 00939
2026-03-27 11:51:47,971 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:47,985 - openbb_akshare.models.equity_search - INFO - Searching for 00939 and found 3 results.
2026-03-27 11:51:47,990 - openbb_app.routes.portfolio - INFO - Found stock name for 00939: 建设银行
2026-03-27 11:51:47,990 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 00998
2026-03-27 11:51:48,004 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,018 - openbb_akshare.models.equity_search - INFO - Searching for 00998 and found 4 results.
2026-03-27 11:51:48,021 - openbb_app.routes.portfolio - INFO - Found stock name for 00998: 中信银行
2026-03-27 11:51:48,022 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 01288
2026-03-27 11:51:48,036 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,049 - openbb_akshare.models.equity_search - INFO - Searching for 01288 and found 4 results.
2026-03-27 11:51:48,052 - openbb_app.routes.portfolio - INFO - Found stock name for 01288: 农业银行
2026-03-27 11:51:48,054 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 01339
2026-03-27 11:51:48,066 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,080 - openbb_akshare.models.equity_search - INFO - Searching for 01339 and found 4 results.
2026-03-27 11:51:48,084 - openbb_app.routes.portfolio - INFO - Found stock name for 01339: 中国人民保险集团
2026-03-27 11:51:48,084 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 01398
2026-03-27 11:51:48,098 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,112 - openbb_akshare.models.equity_search - INFO - Searching for 01398 and found 3 results.
2026-03-27 11:51:48,115 - openbb_app.routes.portfolio - INFO - Found stock name for 01398: 工商银行
2026-03-27 11:51:48,115 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 01658
2026-03-27 11:51:48,129 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,145 - openbb_akshare.models.equity_search - INFO - Searching for 01658 and found 3 results.
2026-03-27 11:51:48,151 - openbb_app.routes.portfolio - INFO - Found stock name for 01658: 邮储银行
2026-03-27 11:51:48,152 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 01919
2026-03-27 11:51:48,171 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,187 - openbb_akshare.models.equity_search - INFO - Searching for 01919 and found 2 results.
2026-03-27 11:51:48,190 - openbb_app.routes.portfolio - INFO - Found stock name for 01919: 中远海控
2026-03-27 11:51:48,191 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 02800
2026-03-27 11:51:48,208 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,223 - openbb_akshare.models.equity_search - INFO - Searching for 02800 and found 2 results.
2026-03-27 11:51:48,226 - openbb_app.routes.portfolio - INFO - Found stock name for 02800: 盈富基金
2026-03-27 11:51:48,226 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 02880
2026-03-27 11:51:48,241 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,257 - openbb_akshare.models.equity_search - INFO - Searching for 02880 and found 2 results.
2026-03-27 11:51:48,260 - openbb_app.routes.portfolio - INFO - Found stock name for 02880: 辽港股份
2026-03-27 11:51:48,260 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 03988
2026-03-27 11:51:48,274 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,289 - openbb_akshare.models.equity_search - INFO - Searching for 03988 and found 2 results.
2026-03-27 11:51:48,293 - openbb_app.routes.portfolio - INFO - Found stock name for 03988: 中国银行
2026-03-27 11:51:48,293 - openbb_app.routes.portfolio - INFO - Searching stock name for symbol: 06823
2026-03-27 11:51:48,306 - openbb_akshare.utils.ak_equity_search - INFO - Loading symbols from openbb_akshare cache...
2026-03-27 11:51:48,322 - openbb_akshare.models.equity_search - INFO - Searching for 06823 and found 1 results.
2026-03-27 11:51:48,325 - openbb_app.routes.portfolio - INFO - Found stock name for 06823: 香港电讯-SS

## 自选股

In [2]:
from openbb_app.routes.portfolio import get_all_stocks

get_all_stocks()

2026-03-20 15:20:37,712 - openbb_app.routes.portfolio - INFO - Using cache directory: C:\Users\roger\OpenBBUserData\cache
2026-03-20 15:20:37,712 - openbb_app.core.database - INFO - Creating directory for database: C:\Users\roger\OpenBBUserData\cache\appdata
2026-03-20 15:20:37,715 - openbb_app.core.database - INFO - Directory created successfully: C:\Users\roger\OpenBBUserData\cache\appdata
2026-03-20 15:20:37,717 - openbb_app.core.utils - INFO - Fetching quote data for 600028.SH
2026-03-20 15:20:37,730 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600028
2026-03-20 15:20:38,594 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600028.SH
2026-03-20 15:20:38,595 - openbb_app.core.utils - INFO - Fetching quote data for 600325.SH
2026-03-20 15:20:38,600 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-03-20 15:20:39,517 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325.SH

[{'symbol': '600028.SH',
  'name': '中国石化',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 6.08,
  'fifty_two_week_low': 5.0466,
  'fifty_two_week_high': 8.11,
  'dividend_yield': 3.766,
  'latest_dividend': 0.229,
  'strategy': '持有',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600028'},
 {'symbol': '600325.SH',
  'name': '华发股份',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 3.85,
  'fifty_two_week_low': 3.85,
  'fifty_two_week_high': 5.74,
  'dividend_yield': 3.221,
  'latest_dividend': 0.124,
  'strategy': '买进',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600325'}]

In [2]:
from openbb_app.routes.portfolio import get_db_manager
db_manager = get_db_manager()

2026-03-20 15:53:28,343 - openbb_app.routes.portfolio - INFO - Using cache directory: C:\Users\roger\OpenBBUserData\cache
2026-03-20 15:53:28,343 - openbb_app.core.database - INFO - Creating directory for database: C:\Users\roger\OpenBBUserData\cache\appdata
2026-03-20 15:53:28,343 - openbb_app.core.database - INFO - Directory created successfully: C:\Users\roger\OpenBBUserData\cache\appdata

In [3]:
db_manager.get_all_portfolio_stocks()

2026-03-20 15:53:31,006 - openbb_app.core.utils - INFO - Fetching quote data for 600028.SH
2026-03-20 15:53:31,021 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600028
2026-03-20 15:53:31,918 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600028.SH
2026-03-20 15:53:31,920 - openbb_app.core.utils - INFO - Fetching quote data for 600325.SH
2026-03-20 15:53:31,925 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-03-20 15:53:32,759 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325.SH

[{'symbol': '600028.SH',
  'name': '中国石化',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 6.08,
  'fifty_two_week_low': 5.0466,
  'fifty_two_week_high': 8.11,
  'dividend_yield': 3.766,
  'latest_dividend': 0.229,
  'strategy': '持有',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600028'},
 {'symbol': '600325.SH',
  'name': '华发股份',
  'avg_cost': 0.0,
  'quantity': 0,
  'total_value': 0.0,
  'current_price': 3.85,
  'fifty_two_week_low': 3.85,
  'fifty_two_week_high': 5.74,
  'dividend_yield': 3.221,
  'latest_dividend': 0.124,
  'strategy': '买进',
  'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600325'}]

In [4]:
db_manager.get_portfolio_stock("600325.SH")

2026-03-20 15:53:36,226 - openbb_app.core.utils - INFO - Fetching quote data for 600325.SH
2026-03-20 15:53:36,231 - openbb_akshare.models.equity_quote - INFO - Fetching data for symbol: SH600325
2026-03-20 15:53:37,124 - openbb_app.core.utils - INFO - Successfully fetched quote data for 600325.SH

{'symbol': '600325.SH',
 'name': '华发股份',
 'avg_cost': 0.0,
 'quantity': 0,
 'total_value': 0.0,
 'current_price': 3.85,
 'fifty_two_week_low': 3.85,
 'fifty_two_week_high': 5.74,
 'dividend_yield': 3.221,
 'latest_dividend': 0.124,
 'strategy': '买进',
 'tradingview': 'https://cn.tradingview.com/chart/?symbol=SSE:600325'}